# -*- coding: utf-8 -*-
"""NB1_train_locomotion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyxKwH8odKACopwEn1BugaLbkWBdd2ng

# NB1 — Robust PPO locomotion policy

Trains **one** robust `locomote` policy on the flat plane with a **wide command sampler**
(`vx∈[-1,2.5], vy∈[-0.8,0.8], wz∈[-1.5,1.5]`) so it can smoothly obey the VLM's bucketed
direction commands later. Checkpoints to Drive (resumable); ends with a **high-quality eval GIF**
(black floor + white grid, lights, shadows) showing command following.

> Run NB0 first. This notebook reloads the shared modules from Drive.
"""

# Reinstall the locomotion stack if this is a fresh runtime (idempotent, ~2-3 min)
import importlib.util
if importlib.util.find_spec('genesis') is None:
    !apt-get install -y -qq xvfb libgl1 libegl1 libosmesa6 libglfw3 libglew2.2 ffmpeg > /dev/null
    !pip install -q genesis-world 'rsl-rl-lib==2.2.4' tensorboard pyvirtualdisplay mediapy 'imageio[ffmpeg]'
import torch; print('torch', torch.__version__, '| CUDA', torch.cuda.is_available())

# Setup: env vars (before genesis), mount Drive, restore shared modules
import os
os.environ['PYOPENGL_PLATFORM'] = 'egl'; os.environ['MUJOCO_GL'] = 'egl'
os.environ['EGL_PLATFORM'] = 'surfaceless'
os.environ['NVIDIA_DRIVER_CAPABILITIES'] = 'compute,graphics,utility'
os.environ['NVIDIA_VISIBLE_DEVICES'] = 'all'
from pyvirtualdisplay import Display
_d = Display(visible=0, size=(1280, 720)); _d.start(); os.environ['DISPLAY'] = f':{_d.display}'

from google.colab import drive; drive.mount('/content/drive', force_remount=False)
import shutil, sys
CFG_DIR = '/content/drive/MyDrive/quadruped_vlm_xai/config'
for f in ['config.py', 'qre_utils.py', 'go2_env.py', 'grid_floor.png', 'config_runtime.json']:
    src = f'{CFG_DIR}/{f}'
    if os.path.exists(src): shutil.copy(src, '/content/' + f)
sys.path.insert(0, '/content')
print('restored:', [f for f in os.listdir('/content') if f.endswith(('.py', '.png', '.json'))])

"""## 1. Write `go2_train.py` (config + PPO training)

`get_cfgs()` returns the reward scales and the **wide** command ranges; PPO is configured via `rsl-rl`.
Supports `--resume_from` and saves to Drive at a fixed interval (plan §5.3).
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/go2_train.py
# import argparse, os, pickle, shutil
# from importlib import metadata
# # Genesis pins an older rsl-rl API — assert the right wheel is installed.
# try:
#     try:
#         if metadata.version("rsl-rl"): raise ImportError
#     except metadata.PackageNotFoundError:
#         if metadata.version("rsl-rl-lib") != "2.2.4": raise ImportError
# except (metadata.PackageNotFoundError, ImportError) as e:
#     raise ImportError("Please install 'rsl-rl-lib==2.2.4'.") from e
# 
# from rsl_rl.runners import OnPolicyRunner
# import genesis as gs
# from go2_env import Go2Env
# 
# def get_train_cfg(exp_name, max_iterations):
#     return {
#         "algorithm": {"class_name": "PPO", "clip_param": 0.2, "desired_kl": 0.01, "entropy_coef": 0.01,
#                       "gamma": 0.99, "lam": 0.95, "learning_rate": 0.001, "max_grad_norm": 1.0,
#                       "num_learning_epochs": 5, "num_mini_batches": 4, "schedule": "adaptive",
#                       "use_clipped_value_loss": True, "value_loss_coef": 1.0},
#         "init_member_classes": {},
#         "policy": {"activation": "elu", "actor_hidden_dims": [512, 256, 128],
#                    "critic_hidden_dims": [512, 256, 128], "init_noise_std": 1.0, "class_name": "ActorCritic"},
#         "runner": {"checkpoint": -1, "experiment_name": exp_name, "load_run": -1, "log_interval": 1,
#                    "max_iterations": max_iterations, "record_interval": -1, "resume": False,
#                    "resume_path": None, "run_name": ""},
#         "runner_class_name": "OnPolicyRunner",
#         "num_steps_per_env": 24, "save_interval": 100, "empirical_normalization": None, "seed": 1,
#     }
# 
# def get_cfgs():
#     env_cfg = {
#         "num_actions": 12,
#         "default_joint_angles": {
#             "FL_hip_joint": 0.0, "FR_hip_joint": 0.0, "RL_hip_joint": 0.0, "RR_hip_joint": 0.0,
#             "FL_thigh_joint": 0.8, "FR_thigh_joint": 0.8, "RL_thigh_joint": 1.0, "RR_thigh_joint": 1.0,
#             "FL_calf_joint": -1.5, "FR_calf_joint": -1.5, "RL_calf_joint": -1.5, "RR_calf_joint": -1.5},
#         "joint_names": ["FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
#                         "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
#                         "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint",
#                         "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint"],
#         "kp": 20.0, "kd": 0.5,
#         "termination_if_roll_greater_than": 10, "termination_if_pitch_greater_than": 10,
#         "base_init_pos": [0.0, 0.0, 0.42], "base_init_quat": [1.0, 0.0, 0.0, 0.0],
#         "episode_length_s": 20.0, "resampling_time_s": 4.0, "action_scale": 0.25,
#         "simulate_action_latency": True, "clip_actions": 100.0,
#     }
#     obs_cfg = {"num_obs": 45, "obs_scales": {"lin_vel": 2.0, "ang_vel": 0.25, "dof_pos": 1.0, "dof_vel": 0.05}}
#     reward_cfg = {"tracking_sigma": 0.25, "base_height_target": 0.3, "feet_height_target": 0.075,
#                   "reward_scales": {"tracking_lin_vel": 1.0, "tracking_ang_vel": 0.2, "lin_vel_z": -1.0,
#                                     "base_height": -50.0, "action_rate": -0.005, "similar_to_default": -0.1}}
#     # WIDE command sampler -> robust to VLM directional commands (plan NB1)
#     command_cfg = {"num_commands": 3, "lin_vel_x_range": [-1.0, 2.5],
#                    "lin_vel_y_range": [-0.8, 0.8], "ang_vel_range": [-1.5, 1.5]}
#     return env_cfg, obs_cfg, reward_cfg, command_cfg
# 
# def main():
#     ap = argparse.ArgumentParser()
#     ap.add_argument("-e", "--exp_name", type=str, default="go2_locomote")
#     ap.add_argument("-B", "--num_envs", type=int, default=4096)
#     ap.add_argument("--max_iterations", type=int, default=600)
#     ap.add_argument("--log_root", type=str, default="logs")
#     ap.add_argument("--resume_from", type=str, default="")
#     args = ap.parse_args()
# 
#     #gs.init(backend=gs.gpu, precision="32", logging_level="warning", performance_mode=True)
#     gs.init(backend=gs.gpu, precision="32", logging_level="warning")
#     log_dir = f"{args.log_root}/{args.exp_name}"
#     env_cfg, obs_cfg, reward_cfg, command_cfg = get_cfgs()
#     train_cfg = get_train_cfg(args.exp_name, args.max_iterations)
# 
#     os.makedirs(log_dir, exist_ok=True)
#     pickle.dump([env_cfg, obs_cfg, reward_cfg, command_cfg, train_cfg],
#                 open(f"{log_dir}/cfgs.pkl", "wb"))
# 
#     env = Go2Env(num_envs=args.num_envs, env_cfg=env_cfg, obs_cfg=obs_cfg,
#                  reward_cfg=reward_cfg, command_cfg=command_cfg, show_viewer=False)
#     runner = OnPolicyRunner(env, train_cfg, log_dir, device=gs.device)
#     if args.resume_from and os.path.exists(args.resume_from):
#         print("Resuming from", args.resume_from); runner.load(args.resume_from)
#     runner.learn(num_learning_iterations=args.max_iterations, init_at_random_ep_len=True)
#     print("Training done. Checkpoints in", log_dir)
# 
# if __name__ == "__main__":
#     main()

"""## 2. Write `go2_eval.py` (high-quality eval GIF on the grid floor)

Loads the trained policy, attaches a recording camera, drives a few scripted command segments
(forward, turn left, turn right), and saves a GIF rendered with the **hi-q grid-floor scene**.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/go2_eval.py
# import argparse, os, pickle, torch
# import numpy as np
# from rsl_rl.runners import OnPolicyRunner
# import genesis as gs
# from go2_env import Go2Env
# 
# def main():
#     ap = argparse.ArgumentParser()
#     ap.add_argument("-e", "--exp_name", type=str, default="go2_locomote")
#     ap.add_argument("--ckpt", type=int, default=-1)
#     ap.add_argument("--log_root", type=str, default="logs")
#     ap.add_argument("--out", type=str, default="/content/eval.gif")
#     ap.add_argument("--grid", type=str, default="/content/grid_floor.png")
#     ap.add_argument("--steps_per_cmd", type=int, default=120)
#     ap.add_argument("--fps", type=int, default=50)
#     args = ap.parse_args()
# 
#     gs.init(backend=gs.gpu, precision="32", logging_level="warning")
#     log_dir = f"{args.log_root}/{args.exp_name}"
#     env_cfg, obs_cfg, reward_cfg, command_cfg, train_cfg = pickle.load(open(f"{log_dir}/cfgs.pkl", "rb"))
#     reward_cfg["reward_scales"] = {}  # quiet eval
# 
#     env = Go2Env(num_envs=1, env_cfg=env_cfg, obs_cfg=obs_cfg, reward_cfg=reward_cfg,
#                  command_cfg=command_cfg, show_viewer=False, attach_camera=True,
#                  camera_res=(960, 640), camera_pos=(2.4, 1.6, 1.1), camera_lookat=(0.3, 0.0, 0.25),
#                  camera_fov=42, hiq=True, grid_texture=args.grid)
# 
#     # pick latest checkpoint if ckpt < 0
#     ckpts = [f for f in os.listdir(log_dir) if f.startswith("model_") and f.endswith(".pt")]
#     if args.ckpt < 0:
#         nums = sorted(int(f[6:-3]) for f in ckpts); ckpt = nums[-1]
#     else:
#         ckpt = args.ckpt
#     runner = OnPolicyRunner(env, train_cfg, log_dir, device=gs.device)
#     runner.load(os.path.join(log_dir, f"model_{ckpt}.pt"))
#     policy = runner.get_inference_policy(device=gs.device)
#     print("Loaded checkpoint", ckpt)
# 
#     # scripted command segments: (vx, vy, wz)
#     segments = [(1.2, 0.0, 0.0), (0.6, 0.0, 1.0), (0.6, 0.0, -1.0), (1.5, 0.0, 0.0)]
#     obs, _ = env.reset()
#     env.camera.start_recording()
#     with torch.no_grad():
#         for (vx, vy, wz) in segments:
#             env.commands[:, 0] = vx; env.commands[:, 1] = vy; env.commands[:, 2] = wz
#             for _ in range(args.steps_per_cmd):
#                 act = policy(obs)
#                 obs, _, _, _ = env.step(act)
#                 env.commands[:, 0] = vx; env.commands[:, 1] = vy; env.commands[:, 2] = wz  # hold command
#                 env.camera.render()
#     env.camera.stop_recording(save_to_filename=args.out, fps=args.fps)
#     print("Wrote", args.out)
# 
# if __name__ == "__main__":
#     main()

"""## 3. Quick sanity gate before the long run

One env, a few steps, assert it does not explode — catches install/asset/EGL problems in seconds.
"""

import importlib, genesis as gs, qre_utils as U
importlib.reload(U)
from go2_train import get_cfgs
from go2_env import Go2Env

gs.init(backend=gs.gpu, precision="32", logging_level="warning")
env_cfg, obs_cfg, reward_cfg, command_cfg = get_cfgs()
env = Go2Env(1, env_cfg, obs_cfg, reward_cfg, command_cfg,
             show_viewer=False, attach_camera=True, camera_res=(640, 480),
             hiq=True, grid_texture='/content/grid_floor.png')
obs, _ = env.reset()
import torch
with torch.no_grad():
    for _ in range(5):
        obs, rew, done, info = env.step(0.05 * torch.randn((1, env.num_actions), device=gs.device))
info = U.sanity_gate(env.scene, env.robot, env.camera, '/content/nb1_sanity.png')
print('NB1 sanity:', info)
from IPython.display import Image, display; display(Image('/content/nb1_sanity.png'))

"""## 4. Train (4096 parallel envs on A100)

`--max_iterations 600` gives a solid gait; bump higher for a smoother one. Checkpoints land in
`logs/go2_locomote/` and are mirrored to Drive after training. To resume a timed-out run,
pass `--resume_from logs/go2_locomote/model_<N>.pt`.
"""

# watch nvidia-smi

# rsl-rl's TensorBoard logging pulls in TensorFlow, whose CUDA init is
# deadlocking on this runtime. We don't need TF — remove it so logging
# falls back to the no-TF event writer.
!pip uninstall -y tensorflow tensorflow-cpu 2>/dev/null
print("tensorflow removed (tensorboard still present for logging)")

import shutil
shutil.rmtree('logs/go2_locomote', ignore_errors=True)
print('cleared smoke-test checkpoints — next run starts fresh')

import os, shutil
os.chdir('/content')
EXP = 'go2_locomote'; NUM_ENVS = 4096; ITERS = 600
# Restore any prior checkpoints from Drive so we can resume
DRIVE_LOG = '/content/drive/MyDrive/quadruped_vlm_xai/logs'
os.makedirs(f'logs/{EXP}', exist_ok=True)
if os.path.isdir(f'{DRIVE_LOG}/{EXP}'):
    for f in os.listdir(f'{DRIVE_LOG}/{EXP}'):
        shutil.copy(f'{DRIVE_LOG}/{EXP}/{f}', f'logs/{EXP}/{f}')
resume = ''
ck = [f for f in os.listdir(f'logs/{EXP}') if f.startswith('model_')]
if ck:
    latest = max(int(f[6:-3]) for f in ck); resume = f'logs/{EXP}/model_{latest}.pt'
    print('Will resume from', resume)

#!python go2_train.py --exp_name {EXP} --num_envs {NUM_ENVS} --max_iterations {ITERS} {('--resume_from ' + resume) if resume else ''}
!python -u go2_train.py --exp_name {EXP} --num_envs {NUM_ENVS} --max_iterations {ITERS} {('--resume_from ' + resume) if resume else ''}

# Mirror checkpoints to Drive
import os, shutil
EXP = 'go2_locomote'
DRIVE_LOG = '/content/drive/MyDrive/quadruped_vlm_xai/logs'
os.makedirs(f'{DRIVE_LOG}/{EXP}', exist_ok=True)
for f in os.listdir(f'logs/{EXP}'):
    src = f'logs/{EXP}/{f}'
    if os.path.isfile(src):  # skip subdirectories like git/
        shutil.copy(src, f'{DRIVE_LOG}/{EXP}/{f}')
print('Checkpoints mirrored to Drive:', sorted(os.listdir(f'{DRIVE_LOG}/{EXP}')))

"""## 5. High-quality eval GIF (the showcase render)

Black floor + white grid, lights, shadows. Shows the policy following forward / left-turn /
right-turn commands — the directional control the VLM will drive in NB2.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/go2_eval.py
# import argparse, os, pickle, torch
# import numpy as np
# from rsl_rl.runners import OnPolicyRunner
# import genesis as gs
# from go2_env import Go2Env
# 
# def main():
#     ap = argparse.ArgumentParser()
#     ap.add_argument("--exp_name", type=str, default="go2_locomote")
#     ap.add_argument("--ckpt", type=int, default=-1)
#     ap.add_argument("--log_root", type=str, default="logs")
#     ap.add_argument("--out", type=str, default="/content/eval.mp4")
#     ap.add_argument("--grid", type=str, default="/content/grid_floor.png")
#     ap.add_argument("--steps_per_cmd", type=int, default=120)
#     ap.add_argument("--fps", type=int, default=50)
#     args = ap.parse_args()
# 
#     gs.init(backend=gs.gpu, precision="32", logging_level="warning")
# 
#     log_dir = f"{args.log_root}/{args.exp_name}"
#     env_cfg, obs_cfg, reward_cfg, command_cfg, train_cfg = pickle.load(open(f"{log_dir}/cfgs.pkl", "rb"))
#     reward_cfg["reward_scales"] = {} # quiet eval
# 
#     env = Go2Env(num_envs=1, env_cfg=env_cfg, obs_cfg=obs_cfg, reward_cfg=reward_cfg,
#                  command_cfg=command_cfg, show_viewer=False, attach_camera=True,
#                  camera_res=(960, 640), camera_pos=(2.4, 1.6, 1.1), camera_lookat=(0.3, 0.0, 0.25),
#                  camera_fov=42, hiq=True, grid_texture=args.grid)
# 
#     ckpts = [f for f in os.listdir(log_dir) if f.startswith("model_") and f.endswith(".pt")]
#     if args.ckpt < 0:
#         nums = sorted([int(f[6:-3]) for f in ckpts])
#         ckpt = nums[-1]
#     else:
#         ckpt = args.ckpt
# 
#     runner = OnPolicyRunner(env, train_cfg, log_dir, device=gs.device)
#     runner.load(os.path.join(log_dir, f"model_{ckpt}.pt"))
#     policy = runner.get_inference_policy(device=gs.device)
#     print("Loaded checkpoint", ckpt)
# 
#     # scripted command segments: (vx, vy, wz)
#     segments = [(1.2, 0.0, 0.0), (0.6, 0.0, 1.0), (0.6, 0.0, -1.0), (1.5, 0.0, 0.0)]
# 
#     obs, _ = env.reset()
#     env.camera.start_recording()
# 
#     with torch.no_grad():
#         for (vx, vy, wz) in segments:
#             env.commands[:, 0] = vx; env.commands[:, 1] = vy; env.commands[:, 2] = wz
#             for i in range(args.steps_per_cmd):
#                 act = policy(obs)
# 
#                 # --- BUG FIX: Unpack all 4 values returned by env.step() ---
#                 obs, rew, done, info = env.step(act)
# 
#                 env.commands[:, 0] = vx; env.commands[:, 1] = vy; env.commands[:, 2] = wz # hold command
# 
#                 # --- CAMERA TRACKING ADDITION ---
#                 # 1. Get the robot's base position (index 0 since num_envs=1)
#                 base_pos = env.robot.get_pos()[0].cpu().numpy()
# 
#                 # 2. Maintain a trailing offset behind and slightly above the robot
#                 cam_pos = (base_pos[0] + 2.1, base_pos[1] + 1.6, 1.1)
#                 cam_lookat = (base_pos[0], base_pos[1], base_pos[2])
# 
#                 # 3. Update the camera pose before rendering
#                 env.camera.set_pose(pos=cam_pos, lookat=cam_lookat)
#                 # --------------------------------
# 
#                 env.camera.render()
# 
#     env.camera.stop_recording(save_to_filename=args.out, fps=args.fps)
#     print("Wrote", args.out)
# 
# if __name__ == "__main__":
#     main()

import os
os.chdir('/content')

# Render as MP4 to resolve the MoviePy/FFmpeg codec mismatch
!python go2_eval.py \
  --exp_name go2_locomote \
  --grid /content/grid_floor.png \
  --out /content/eval.mp4 \
  --steps_per_cmd 120 \
  --fps 50

# Copy to Drive
import shutil
shutil.copy('/content/eval.mp4', '/content/drive/MyDrive/quadruped_vlm_xai/videos/nb1_eval.mp4')

# Display in Colab
import mediapy as media

# mediapy can read and display the MP4 directly
video = media.read_video('/content/eval.mp4')
media.show_video(video, fps=50)

"""## ✅ NB1 acceptance checklist
- [ ] Sanity gate passes (no fall-over / launch-away)
- [ ] PPO trained for the chosen iterations; checkpoints in `logs/go2_locomote/` and mirrored to Drive
- [ ] Hi-q eval GIF shows a stable gait turning left, right, and walking forward on the black/white-grid floor

**Next:** NB2 wires Qwen2.5-VL into the loop and builds the two-goal arena.
"""