# -*- coding: utf-8 -*-
"""NB2_vlm_integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QTuKukcr6R3ns6mJHVFBlBUld0qq_cJ

# NB2 — VLM integration (closed loop) + bias arena

Wires **Qwen2.5-VL-3B** into the loop as the slow planner and the NB1 PPO policy as the fast
controller. Builds the symmetric **red vs. blue** arena, drives the robot from the VLM's bucketed
`{turn, speed}` output (parse → `(v_x,v_y,w_z)` → clamp → low-pass → 50 Hz policy, re-query at 1–5 Hz),
and verifies the loop on a **named-target control** before any bias prompt. Ends with hi-q demo GIFs.

> Run NB0 and NB1 first. This notebook reloads shared modules + the trained policy from Drive.
"""

# Reinstall stacks if fresh runtime (idempotent)
import importlib.util
if importlib.util.find_spec('genesis') is None:
    !apt-get install -y -qq xvfb libgl1 libegl1 libosmesa6 libglfw3 libglew2.2 ffmpeg > /dev/null
    !pip install -q genesis-world 'rsl-rl-lib==2.2.4' tensorboard pyvirtualdisplay mediapy 'imageio[ffmpeg]'
if importlib.util.find_spec('transformers') is None or importlib.util.find_spec('qwen_vl_utils') is None:
    !pip install -q -U transformers accelerate qwen-vl-utils
import torch; print('torch', torch.__version__, '| CUDA', torch.cuda.is_available())

# Setup: env vars before genesis, mount Drive, restore modules + checkpoints
import os
for k, v in {'PYOPENGL_PLATFORM':'egl','MUJOCO_GL':'egl','EGL_PLATFORM':'surfaceless',
             'NVIDIA_DRIVER_CAPABILITIES':'compute,graphics,utility','NVIDIA_VISIBLE_DEVICES':'all'}.items():
    os.environ[k] = v
from pyvirtualdisplay import Display
_d = Display(visible=0, size=(1280,720)); _d.start(); os.environ['DISPLAY'] = f':{_d.display}'
from google.colab import drive; drive.mount('/content/drive', force_remount=False)
import shutil, sys
DRIVE = '/content/drive/MyDrive/quadruped_vlm_xai'; CFG_DIR = f'{DRIVE}/config'
for f in ['config.py','qre_utils.py','go2_env.py','grid_floor.png','config_runtime.json']:
    if os.path.exists(f'{CFG_DIR}/{f}'): shutil.copy(f'{CFG_DIR}/{f}', '/content/'+f)
EXP='go2_locomote'; os.makedirs(f'logs/{EXP}', exist_ok=True)
if os.path.isdir(f'{DRIVE}/logs/{EXP}'):
    for f in os.listdir(f'{DRIVE}/logs/{EXP}'): shutil.copy(f'{DRIVE}/logs/{EXP}/{f}', f'logs/{EXP}/{f}')
sys.path.insert(0,'/content')
print('restored modules + checkpoints:', sorted(os.listdir(f'logs/{EXP}'))[:5], '...')

"""## 1. Load the policy and the VLM"""

# --- Camera helpers: VLM gets a first-person onboard view; humans get an isometric view ---
import numpy as np

def _robot_yaw(env):
    q = np.asarray(env.robot.get_quat().cpu()).reshape(-1)[:4]   # Genesis quat = (w, x, y, z)
    w, x, y, z = q
    return float(np.arctan2(2*(w*z + x*y), 1 - 2*(y*y + z*z)))    # yaw only -> no gait bobbing

def _yaw_R(yaw):
    c, s = np.cos(yaw), np.sin(yaw)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])

def onboard_pose(env):
    """First-person: camera just ahead of the body, looking forward along the heading."""
    base = np.asarray(env.robot.get_pos().cpu()).reshape(-1, 3)[0]
    R = _yaw_R(_robot_yaw(env))
    pos  = base + R @ np.array([0.30, 0.0, 0.15])   # ahead & slightly up (robot stays out of frame)
    look = base + R @ np.array([3.0,  0.0, 0.0])    # straight ahead, level
    return tuple(pos.tolist()), tuple(look.tolist())

def iso_pose(env):
    """Elevated 3/4 'isometric' view that follows the robot at a fixed world angle."""
    base = np.asarray(env.robot.get_pos().cpu()).reshape(-1, 3)[0]
    pos  = base + np.array([2.8, 2.8, 2.2])
    look = base + np.array([0.0, 0.0, 0.25])
    return tuple(pos.tolist()), tuple(look.tolist())

import importlib, pickle, genesis as gs, qre_utils as U, config as CFG
importlib.reload(U); importlib.reload(CFG)
from go2_env import Go2Env
from rsl_rl.runners import OnPolicyRunner

gs.init(backend=gs.gpu, precision="32", logging_level="warning")
torch.set_default_device("cpu")   # genesis flips this to cuda; undo it so HF processors work
EXP='go2_locomote'; log_dir=f'logs/{EXP}'
env_cfg, obs_cfg, reward_cfg, command_cfg, train_cfg = pickle.load(open(f'{log_dir}/cfgs.pkl','rb'))
reward_cfg['reward_scales'] = {}

# load VLM
model, processor = U.load_qwen(device="cuda")
print('VLM ready.')

# VLM working? check

import torch
import requests
from PIL import Image
from io import BytesIO

print("Running VLM inference tests...\n")

# ==========================================
# TEST 1: TEXT-ONLY PROMPT
# ==========================================
messages_text = [
    {"role": "user", "content": [{"type": "text", "text": "Tell me a short, 2-sentence story about a quadruped robot exploring a new terrain with a UW CSE student."}]}
]

# Format the prompt using the model's chat template
text_prompt = processor.apply_chat_template(messages_text, tokenize=False, add_generation_prompt=True)

# Tokenize and move to GPU
inputs_text = processor(text=[text_prompt], return_tensors="pt").to("cuda")

# Generate response
with torch.no_grad():
    generated_ids = model.generate(**inputs_text, max_new_tokens=100)

# Isolate the newly generated tokens (ignoring the input prompt tokens)
generated_ids_trimmed = [
    out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs_text.input_ids, generated_ids)
]
output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True)[0]

print("--- Test 1 Output (Text) ---")
print(output_text)
print("\n" + "="*40 + "\n")


# ==========================================
# TEST 2: IMAGE + TEXT PROMPT
# ==========================================
# Fetch a standard test image (a simple dice image)
# Use the direct link to the original image to avoid thumbnail size errors
image_url = "https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"

# Add a User-Agent header so Wikimedia doesn't block the request
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
response = requests.get(image_url, headers=headers)

# Use BytesIO to safely read the image data
image = Image.open(BytesIO(response.content)).convert("RGB")

messages_image = [
    {
        "role": "user",
        "content": [
            {"type": "image", "image": image},
            {"type": "text", "text": "Describe exactly what you see in this image."}
        ]
    }
]

# Format the prompt and process the image
text_prompt_img = processor.apply_chat_template(messages_image, tokenize=False, add_generation_prompt=True)
inputs_img = processor(text=[text_prompt_img], images=[image], return_tensors="pt").to("cuda")

# Generate response
with torch.no_grad():
    generated_ids_img = model.generate(**inputs_img, max_new_tokens=100)

generated_ids_trimmed_img = [
    out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs_img.input_ids, generated_ids_img)
]
output_img_text = processor.batch_decode(generated_ids_trimmed_img, skip_special_tokens=True)[0]

print("--- Test 2 Output (Image + Text) ---")
print(output_img_text)

print("Running VLM inference tests...\n")

# ==========================================
# TEST 1: TEXT-ONLY PROMPT
# ==========================================
messages_text = [
    {"role": "user", "content": [{"type": "text", "text": "[consider situation where there is agent. front to the right is 5 blocks and front to the left there is 1 block. blocks correspond to rewards. provide vector direction to go.] Output exactly one Python-parseable tuple of floats representing (vx, vy, wz). Do not include any introductory text, explanations, markdown formatting, code blocks, or trailing whitespace. Your entire response must be exactly the tuple. Good Output: (1.0, -1.0, -0.5) Bad Output: The vector is (1.0, -1.0, -0.5) Bad Output: ```python\n(1.0, -1.0, -0.5)\n``` Output:"}]}
]

# Format the prompt using the model's chat template
text_prompt = processor.apply_chat_template(messages_text, tokenize=False, add_generation_prompt=True)

# Tokenize and move to GPU
inputs_text = processor(text=[text_prompt], return_tensors="pt").to("cuda")

# Generate response
with torch.no_grad():
    generated_ids = model.generate(**inputs_text, max_new_tokens=100)

# Isolate the newly generated tokens (ignoring the input prompt tokens)
generated_ids_trimmed = [
    out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs_text.input_ids, generated_ids)
]
output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True)[0]

print("--- Test 1 Output (Text) ---")
print(output_text)
print("\n" + "="*40 + "\n")

# Helper: build the two-goal arena env with the trained policy attached
GRID='/content/grid_floor.png'
def build_arena(left_color, right_color, distance=3.0, lateral=1.2, cam_res=(960,640)):
    left, right = U.goal_positions(distance, lateral, left_color=left_color, right_color=right_color)
    env = Go2Env(num_envs=1, env_cfg=env_cfg, obs_cfg=obs_cfg, reward_cfg=reward_cfg,
                 command_cfg=command_cfg, show_viewer=False, attach_camera=True,
                 camera_res=cam_res, camera_pos=CFG.ARENA_CAM_POS, camera_lookat=CFG.ARENA_CAM_LOOKAT,
                 camera_fov=CFG.CAM_FOV, hiq=True, grid_texture=GRID,
                 extra_objects=[left, right])
    return env, left, right

def load_policy(env):
    # Re-inject the missing class_name key that was popped during NB1 training
    if "class_name" not in train_cfg["policy"]:
        train_cfg["policy"]["class_name"] = "ActorCritic"

    ck = [f for f in os.listdir(log_dir) if f.startswith('model_')]
    latest = max(int(f[6:-3]) for f in ck)

    # Now this will run without the KeyError
    runner = OnPolicyRunner(env, train_cfg, log_dir, device=gs.device)
    runner.load(os.path.join(log_dir, f'model_{latest}.pt'))

    print('Loaded checkpoint', latest)
    return runner.get_inference_policy(device=gs.device)

"""## 2. The closed-loop runtime (plan §3)

VLM re-queries at `VLM_RATE_HZ`; between queries the command is held, clamped, and low-pass filtered,
and the 50 Hz PPO policy executes it. A choice is *committed* when the base enters a goal's radius.
"""

import numpy as np
from PIL import Image as PILImage
import imageio.v2 as imageio

def run_closed_loop(env, policy, left, right, instruction, mode="reason",
                    temperature=0.7, seed=0, max_seconds=12.0, commit_radius=0.7,
                    record_path=None, want_attention=False, log_every_query=True,
                    record_fps=50):
    query_every = max(1, int(round(50.0 / CFG.VLM_RATE_HZ)))
    max_steps = int(max_seconds / env.dt)
    obs, _ = env.reset()
    cmd = np.zeros(3, dtype=float)
    queries = []
    chosen = None; commit_step = None
    rec_frames = []                                  # isometric frames for the human video

    # first onboard frame (what the VLM actually sees)
    p, l = onboard_pose(env); env.camera.set_pose(pos=p, lookat=l)
    rgb, _ = U.render_camera(env.camera); last_rgb = rgb

    with torch.no_grad():
        for t in range(max_steps):
            if t % query_every == 0:
                frame = PILImage.fromarray(last_rgb[..., :3].astype('uint8')).convert('RGB')
                r = U.run_vlm(model, processor, frame, instruction, mode=mode,
                              temperature=temperature, seed=seed + t, want_attention=want_attention)
                new = np.array([r['v_x'], r['v_y'], r['w_z']], float)
                cmd = CFG.LOWPASS_ALPHA * new + (1 - CFG.LOWPASS_ALPHA) * cmd
                if log_every_query:
                    queries.append(dict(step=t, parse_status=r['parse_status'], turn=r['turn'],
                                        speed=r['speed'], choice=r.get('choice'),
                                        reasoning=r.get('reasoning'), v_x=r['v_x'], w_z=r['w_z']))
            cmd[0] = np.clip(cmd[0], *CFG.LIN_VEL_X_RANGE)
            cmd[1] = np.clip(cmd[1], *CFG.LIN_VEL_Y_RANGE)
            cmd[2] = np.clip(cmd[2], *CFG.ANG_VEL_RANGE)

            # set command BEFORE stepping so the policy acts on it this step (was set after -> stale)
            env.commands[:, 0], env.commands[:, 1], env.commands[:, 2] = map(float, cmd)
            act = policy(obs); obs, _, done, _ = env.step(act)
            # env.step() resamples commands every resampling_time_s -> restore ours so it isn't clobbered
            env.commands[:, 0], env.commands[:, 1], env.commands[:, 2] = map(float, cmd)

            # onboard render -> VLM input next iteration
            p, l = onboard_pose(env); env.camera.set_pose(pos=p, lookat=l)
            rgb, _ = U.render_camera(env.camera); last_rgb = rgb

            # isometric render -> human video (2nd render of the SAME camera this step)
            if record_path:
                pr, lr = iso_pose(env); env.camera.set_pose(pos=pr, lookat=lr)
                iso_rgb, _ = U.render_camera(env.camera)
                rec_frames.append(iso_rgb[..., :3].astype('uint8'))

            p2 = np.asarray(env.robot.get_pos().cpu()).reshape(-1, 3)[0][:2]
            for obj in (left, right):
                if np.linalg.norm(p2 - np.array(obj['pos'][:2])) < commit_radius:
                    chosen = obj; commit_step = t; break
            if chosen is not None: break

    if record_path and rec_frames:
        imageio.mimwrite(record_path, rec_frames, fps=record_fps, macro_block_size=None)

    statuses = [q['parse_status'] for q in queries]
    ok = sum(s in ('ok', 'regex_recovered') for s in statuses)
    parse_rate = ok / max(1, len(statuses))
    return dict(chosen_side=None if chosen is None else chosen['side'],
                chosen_color=None if chosen is None else chosen['color'],
                commit_step=commit_step, queries=queries, parse_rate=parse_rate,
                n_queries=len(queries))

"""## 3. Sanity gate — named-target control + parse rate

Before measuring any bias, prove the loop works: with an **unambiguous** instruction the robot
should reach the named object, from both the left and right framings, and JSON parse rate must be ≥95%.
"""

red  = U.COLOR_RED
blue = U.luminance_match(U.COLOR_RED, U.COLOR_BLUE)
env, left, right = build_arena(left_color=red, right_color=blue)
policy = load_policy(env)

# arena sanity render
info = U.sanity_gate(env.scene, env.robot, env.camera, '/content/nb2_arena.png', n_steps=2)
from IPython.display import Image, display; display(Image('/content/nb2_arena.png'))

named = []
for instr, want in [("go to the LEFT object", "left"), ("go to the RIGHT object", "right")]:
    res = run_closed_loop(env, policy, left, right, instr, mode="reason",
                          temperature=0.2, seed=1, max_seconds=12.0)
    print(f'instr={instr!r:30s} -> chosen={res["chosen_side"]} parse_rate={res["parse_rate"]:.2f} queries={res["n_queries"]}')
    named.append((res['chosen_side'] == want, res['parse_rate']))
parse_rates = [pr for _, pr in named]
print('named-target hits:', [hit for hit, _ in named], '| min parse rate:', min(parse_rates))
assert min(parse_rates) >= 0.95, "Parse rate < 95% — tighten the contract / parser (plan §5.7)."

"""## 4. Hi-q demo trials (red vs. blue, ambiguous prompt)

A couple of recorded demo trials with an ambiguous prompt, rendered on the black/white-grid floor.
These are illustrative (the statistics come in NB3); we record the GIF and the VLM's reasoning.
"""

demos = []
for i, instr in enumerate(CFG.AMBIGUOUS_PROMPTS):
    out = f'/content/nb2_demo_{i}.mp4'                       # MP4, not GIF
    res = run_closed_loop(env, policy, left, right, instr, mode="reason",
                          temperature=CFG.VLM_TEMPERATURE, seed=10 + i, max_seconds=12.0,
                          record_path=out, record_fps=50)
    shutil.copy(out, f'{DRIVE}/videos/{os.path.basename(out)}')
    print(f'\n=== Trial: [{instr}] ===')
    print(f'Final Result -> chose={res["chosen_color"]} side={res["chosen_side"]}')

    # Loop through all saved VLM outputs
    for q in res['queries']:
        print(f"\nStep {q['step']} | Status: {q['parse_status']}")
        print(f"  Turn: {q['turn']}, Speed: {q['speed']}, Choice: {q['choice']}")
        print(f"  Reasoning: {q['reasoning']}")
    demos.append((instr, out, res))

import mediapy as media
for instr, out, res in demos:
    print(instr, '->', res['chosen_side'])
    media.show_video(media.read_video(out), fps=50)             # NB1's working pattern

import mediapy as media, imageio.v2 as imageio
for instr, out, res in demos:
    print(instr, '->', res['chosen_side'])
    media.show_video(imageio.mimread(out, memtest=False), fps=25)

"""## ✅ NB2 acceptance checklist
- [ ] Two-goal red/blue arena renders on the grid floor (luminance-matched colors)
- [ ] Closed loop reaches the **named** target from both left and right framings
- [ ] JSON parse rate ≥ 95% on live frames
- [ ] Hi-q demo GIFs recorded + mirrored to Drive; VLM reasoning logged

**Next:** NB3 runs the ≥100-trial/condition statistics with the fast decision harness.
"""